# frozen_string_literal: true

# Generated by queria-backend/scripts/generate_homebrew_formula.sh
# Release: cli-v0.3.0  Repo: nandocoeg2/queria-backend
# Do not hand-edit sha256; re-run the script after each CLI release.
# Archive layout: queria-cli-<triple>/queria-cli — brew chdirs into the single
# top-level dir, so install is bin.install "queria-cli" (not a nested path).

class QueriaCli < Formula
  desc "QuerIa CLI for laptop index-here (Needs review ingest)"
  homepage "https://github.com/nandocoeg2/queria-backend"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/nandocoeg2/queria-backend/releases/download/cli-v0.3.0/queria-cli-aarch64-apple-darwin.tar.gz"
      sha256 "63101cf5b484ef2242edddd1005e1095513467d759e72f3afef58042a05e8c20"
    end
    on_intel do
      url "https://github.com/nandocoeg2/queria-backend/releases/download/cli-v0.3.0/queria-cli-x86_64-apple-darwin.tar.gz"
      sha256 "eed78888739bff371b8d99458d03ee8633d31162f7c58a32fc38730f42581d56"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/nandocoeg2/queria-backend/releases/download/cli-v0.3.0/queria-cli-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "e9cdda650d1c3608439a2fbb5552b6d4d368f4041c866ede9285c08841f32983"
    end
    on_intel do
      url "https://github.com/nandocoeg2/queria-backend/releases/download/cli-v0.3.0/queria-cli-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "40934eab0d3840ff46c511ef724b5d0bc3359cedbe847671e42af1484f2a769b"
    end
  end

  def install
    bin.install "queria-cli"
  end

  test do
    assert_match "index-here", shell_output("#{bin}/queria-cli index-here --help")
  end
end
