# frozen_string_literal: true

# Generated by queria-backend/scripts/generate_homebrew_formula.sh
# Release: cli-v0.3.2  Repo: nandocoeg2/queria-backend
# Do not hand-edit sha256; re-run the script after each CLI release.
# Archive layout: queria-cli-<triple>/queria-cli — brew chdirs into the single
# top-level dir, so install is bin.install "queria-cli" (not a nested path).
# Private queria-backend: urls are Releases API asset endpoints.
# brew requires: export HOMEBREW_GITHUB_API_TOKEN=ghp_… (repo read)
# (plain github.com/.../releases/download/ URLs return 404 for private repos).

class QueriaCli < Formula
  desc "QuerIa CLI for laptop index-here + hub TUI (doctor/index/status)"
  homepage "https://github.com/nandocoeg2/queria-backend"
  version "0.3.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://api.github.com/repos/nandocoeg2/queria-backend/releases/assets/486086187",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: Bearer #{ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", ENV.fetch("GH_TOKEN", ENV.fetch("GITHUB_TOKEN", "")))}",
          ]
      sha256 "fd1f448db128fbf42dff32b068c0a80ddeb5557878bbd3d36a3aff6045a8d2af"
    end
    on_intel do
      url "https://api.github.com/repos/nandocoeg2/queria-backend/releases/assets/486086189",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: Bearer #{ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", ENV.fetch("GH_TOKEN", ENV.fetch("GITHUB_TOKEN", "")))}",
          ]
      sha256 "dcdf81521bf4dbfc0c3d429420dde6247ecb9664af1a83a4b2142ef5840390d7"
    end
  end

  on_linux do
    on_arm do
      url "https://api.github.com/repos/nandocoeg2/queria-backend/releases/assets/486086186",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: Bearer #{ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", ENV.fetch("GH_TOKEN", ENV.fetch("GITHUB_TOKEN", "")))}",
          ]
      sha256 "6c6c5dc1374bee97fdbb2a1b36b1d771ace24b0d1f09ee6e12fbb250fe50bfda"
    end
    on_intel do
      url "https://api.github.com/repos/nandocoeg2/queria-backend/releases/assets/486086183",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: Bearer #{ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", ENV.fetch("GH_TOKEN", ENV.fetch("GITHUB_TOKEN", "")))}",
          ]
      sha256 "2a8e731982cd81156981b99d6a1f9aa9a5042646dcc823c23826056d9d2a1b8e"
    end
  end

  def install
    bin.install "queria-cli"
  end

  test do
    assert_match "index-here", shell_output("#{bin}/queria-cli index-here --help")
  end
end
