# frozen_string_literal: true

# Generated by queria-backend/scripts/generate_homebrew_formula.sh
# Release: cli-v0.3.3  Repo: nandocoeg2/queria-backend
# Do not hand-edit sha256; re-run the script after each CLI release.
# Archive layout: queria-cli-<triple>/queria-cli — brew chdirs into the single
# top-level dir, so install is bin.install "queria-cli" (not a nested path).
# Private queria-backend: urls are Releases API asset endpoints.
# brew requires: export HOMEBREW_GITHUB_API_TOKEN=ghp_… (repo read)
# (plain github.com/.../releases/download/ URLs return 404 for private repos).

class QueriaCli < Formula
  desc "QuerIa CLI for laptop index-here + hub TUI (doctor/index/status)"
  homepage "https://github.com/nandocoeg2/queria-backend"
  version "0.3.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://api.github.com/repos/nandocoeg2/queria-backend/releases/assets/486511240",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: Bearer #{ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", ENV.fetch("GH_TOKEN", ENV.fetch("GITHUB_TOKEN", "")))}",
          ]
      sha256 "71b2fad27b238076e978d5ef88ab1c764948cb2d68931be9d6f544bc5328379a"
    end
    on_intel do
      url "https://api.github.com/repos/nandocoeg2/queria-backend/releases/assets/486511242",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: Bearer #{ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", ENV.fetch("GH_TOKEN", ENV.fetch("GITHUB_TOKEN", "")))}",
          ]
      sha256 "055e9bb4b60306c6581915746ff84e472f8aa7185c42bec1e6af25efbf511c24"
    end
  end

  on_linux do
    on_arm do
      url "https://api.github.com/repos/nandocoeg2/queria-backend/releases/assets/486511238",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: Bearer #{ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", ENV.fetch("GH_TOKEN", ENV.fetch("GITHUB_TOKEN", "")))}",
          ]
      sha256 "e3144911b610c6b52dd0b63b36fef3228694aaae9ac37978c631d201292a45e4"
    end
    on_intel do
      url "https://api.github.com/repos/nandocoeg2/queria-backend/releases/assets/486511244",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: Bearer #{ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", ENV.fetch("GH_TOKEN", ENV.fetch("GITHUB_TOKEN", "")))}",
          ]
      sha256 "ca107ea1253651fabc86d792275ad955d2ed5b7c2bf48cbd6c58318433d5a7da"
    end
  end

  def install
    bin.install "queria-cli"
  end

  test do
    assert_match "index-here", shell_output("#{bin}/queria-cli index-here --help")
  end
end
